### ISSUE TITLE
Edge VM mis-configuration on nsxt 2.4.1 pipeline

### ISSUE THREAD

**Issue by sgrman** [vmware/nsx-t-datacenter-ci-pipelines#66]
Hello,
Running 2.4.1 pipeline.  Pipeline finishes successfully, however the edge VMs are mis-configured.   The normal config should be vNIC0=management, vNIC1=TEP network, vNIC2=Uplink, vNIC=unused or mgmt.  The pipeline has vNIC 1 & vNIC2 reversed.     
Screenshots are attached.  

Thanks 
Scottie

The parameter file variable screen shot is also attached for my environment.
<img width="440" alt="Screen Shot 2019-07-24 at 16 29 20" src="https://user-images.githubusercontent.com/19333241/61837039-94de8480-ae48-11e9-9625-8bb4bbd553dd.png">
<img width="1408" alt="Screen Shot 2019-07-24 at 16 29 35" src="https://user-images.githubusercontent.com/19333241/61837040-94de8480-ae48-11e9-94a6-50abc46f7d80.png">
<img width="521" alt="Screen Shot 2019-07-24 at 16 39 45" src="https://user-images.githubusercontent.com/19333241/61837041-94de8480-ae48-11e9-9858-2908f3ceee85.png">
<img width="527" alt="Screen Shot 2019-07-24 at 16 39 54" src="https://user-images.githubusercontent.com/19333241/61837042-95771b00-ae48-11e9-9936-3e038d675793.png">
<img width="757" alt="Screen Shot 2019-07-24 at 17 27 08" src="https://user-images.githubusercontent.com/19333241/61837043-95771b00-ae48-11e9-9a5c-67d9507eee1e.png">

**Comment by Dyanngg** [comment]
@sgrman This should be fixed in merged PR#61. Please give it another try. Thanks!

**Comment by sgrman** [comment]
@Dyanngg check out https://github.com/vmware/nsx-t-datacenter-ci-pipelines/commit/caeb4ab7740531368933fd795c4b5c3eb7a124e0  I ran this from master 6 days ago, and I am still not sure this is correct... can we Slack...

**Comment by sgrman** [comment]
@Dyanngg think I figured it out...will test
